"""HTTP API: admin endpoints + shared AppState + middleware.

Single aiohttp listener on 0.0.0.0:CREDPROXY_HTTP_PORT serves both this
module's admin routes and bootstrap.py's workspace-facing routes.
Workspace reaches it via the iptables sentinel:80 -> port redirect;
host reaches it via docker -p 127.0.0.1:port.

Trust model:
- /admin/config requires `Authorization: Bearer <token>` matching the
  host-side .run/auth.token, bind-mounted read-only into the proxy at
  $CREDPROXY_TOKEN_PATH. The file is read fresh on every request, so
  rotating the host file takes effect without a proxy restart.
- fetch_metadata_guard rejects cross-origin browser requests; together
  with Chrome's Private Network Access default-deny (we never set
  Access-Control-Allow-Private-Network), this covers the browser
  threat without a shared secret.

Lifecycle: the token is owned by the host (.run/auth.token, mode 0644,
generated by `credproxy start` if absent) and bind-mounted read-only
into the proxy. Config lives on tmpfs at $CREDPROXY_TMPFS/config.json
-- survives SIGHUP-triggered python re-exec (`credproxy reload`);
re-pushed by `credproxy config` after a full container restart.
"""
import hmac
import json
import os
from dataclasses import dataclass, field
from pathlib import Path

from aiohttp import web

import config
from config import BindingCredentials, Credentials

TOKEN_PATH = Path(os.environ["CREDPROXY_TOKEN_PATH"])
CONFIG_PATH = Path(os.environ["CREDPROXY_TMPFS"]) / "config.json"


@dataclass
class AppState:
    creds: Credentials = field(default_factory=lambda: BindingCredentials({}))


STATE_KEY: web.AppKey[AppState] = web.AppKey("state", AppState)


def load_initial_state() -> AppState:
    """Boot-time sanity check + optional config load.

    The token is re-read per request, not stored; this just fails fast
    if the bind mount is missing or empty.
    """
    if not TOKEN_PATH.exists():
        raise SystemExit(
            f"[admin] {TOKEN_PATH} missing -- expected the host token to "
            f"be bind-mounted at this path"
        )
    if not TOKEN_PATH.read_text().strip():
        raise SystemExit(f"[admin] {TOKEN_PATH} is empty")

    if not CONFIG_PATH.exists():
        return AppState()
    try:
        creds = config.load_resolved(
            json.loads(CONFIG_PATH.read_text()), source=str(CONFIG_PATH)
        )
    except config.ConfigError as e:
        raise SystemExit(f"[admin] persisted config invalid: {e}")
    return AppState(creds=creds)


# ---- Middleware ----


@web.middleware
async def fetch_metadata_guard(request: web.Request, handler):
    """Reject cross-origin browser requests.

    Sec-Fetch-Site is a forbidden header name (browsers set it; JS
    cannot override). If present, require same-origin or none; if
    absent, the client isn't a browser -- allow.
    """
    sfs = request.headers.get("Sec-Fetch-Site")
    if sfs is not None and sfs not in ("same-origin", "none"):
        return web.json_response(
            {"error": "cross-origin requests forbidden"}, status=403
        )
    return await handler(request)


@web.middleware
async def no_store(request: web.Request, handler):
    resp = await handler(request)
    if isinstance(resp, web.StreamResponse):
        resp.headers["Cache-Control"] = "no-store"
    return resp


@web.middleware
async def access_log(request: web.Request, handler):
    import log
    log.emit("api", method=request.method, path=request.path)
    return await handler(request)


# ---- Admin handlers ----


def _auth_error(request: web.Request) -> web.Response | None:
    """Bearer-auth an /admin/* request. Returns an error Response to send, or
    None when the token is valid. The token is read from the bind mount per
    call, so host-side rotation works without a proxy restart."""
    header = request.headers.get("Authorization", "")
    scheme, _, presented = header.partition(" ")
    if scheme != "Bearer" or not presented:
        return web.json_response(
            {"error": "expected `Authorization: Bearer <token>`"}, status=401)
    try:
        token = TOKEN_PATH.read_text().strip()
    except OSError:
        return web.json_response({"error": "auth file unavailable"}, status=503)
    if not token or not hmac.compare_digest(presented, token):
        return web.json_response({"error": "invalid token"}, status=401)
    return None


async def admin_config(request: web.Request) -> web.Response:
    """POST /admin/config -- bearer-gated config push/reload."""
    state = request.app[STATE_KEY]

    # Authenticate before any body processing so unauthenticated probes can't
    # fingerprint config schema by reading 400 errors.
    err = _auth_error(request)
    if err is not None:
        return err

    try:
        body = await request.json()
    except json.JSONDecodeError:
        return web.json_response({"error": "invalid JSON body"}, status=400)

    try:
        new_creds = config.load_resolved(body, source="POST /admin/config")
    except config.ConfigError as e:
        return web.json_response({"error": str(e)}, status=400)

    # Carry the live runtime (re-seal) layer across the swap, so a routine
    # re-push (apply/start) doesn't drop an in-flight minted token's dynamic
    # placeholder. The static pushed layer is replaced; the runtime layer is
    # augmentable, not baked immutable at push time.
    new_creds.adopt_runtime(state.creds)

    # The whole body (including an optional `fingerprint` the host sends to mark
    # this config version) is persisted to tmpfs; load_resolved ignores keys
    # other than `bindings`.
    _atomic_write(CONFIG_PATH, json.dumps(body).encode(), 0o400)
    state.creds = new_creds
    return web.json_response({"ok": True})


async def admin_config_get(request: web.Request) -> web.Response:
    """GET /admin/config -- bearer-gated. Report whether config is currently
    loaded and its `fingerprint`, so the host can skip a redundant re-push (the
    `enter` fast path) when the proxy already holds the intended config. Config
    lives on tmpfs, so a restarted proxy reports `loaded: false` and the host
    re-pushes."""
    err = _auth_error(request)
    if err is not None:
        return err
    loaded = False
    fingerprint = None
    if CONFIG_PATH.exists():
        try:
            fingerprint = json.loads(CONFIG_PATH.read_text()).get("fingerprint")
            loaded = True
        except (OSError, json.JSONDecodeError):
            loaded = False
    return web.json_response({"loaded": loaded, "fingerprint": fingerprint})


async def admin_rule_test(request: web.Request) -> web.Response:
    """POST /admin/rule-test -- bearer-gated authoritative dry-run for the CLI's
    `rule test --live`. Body `{method, url}`. Runs the proxy's OWN rule matcher
    against the LOADED config and returns the ordered matches with exact per-script
    phase (from the compiled schemes) plus the intercept decision -- the ground
    truth the host-side matcher can only approximate. Read-only (no state change)."""
    from urllib.parse import urlsplit

    state = request.app[STATE_KEY]
    err = _auth_error(request)
    if err is not None:
        return err
    try:
        body = await request.json()
    except json.JSONDecodeError:
        return web.json_response({"error": "invalid JSON body"}, status=400)
    method, url = body.get("method"), body.get("url")
    if not isinstance(method, str) or not method or not isinstance(url, str) or not url:
        return web.json_response(
            {"error": "expected {method: str, url: str}"}, status=400)
    # Tolerate a bare host/path (no scheme) as well as a full URL.
    parts = urlsplit(url if "://" in url else "//" + url)
    host = (parts.hostname or "").lower()
    path = parts.path or "/"
    creds = state.creds
    return web.json_response({
        "method": method.upper(), "host": host, "path": path,
        "intercepted": creds.intercepts(host),
        "matches": creds.rule_set().dry_run(method, host, path),
    })


def _atomic_write(path: Path, data: bytes, mode: int) -> None:
    tmp = str(path) + ".tmp"
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    with os.fdopen(fd, "wb") as f:
        f.write(data)
    os.replace(tmp, path)


admin_routes = [
    web.post("/admin/config", admin_config),
    web.get("/admin/config", admin_config_get),
    web.post("/admin/rule-test", admin_rule_test),
]
